version: "3.1"

services:
  application:
    container_name: shopify_ui
    build: .
    # command: sleep infinity
    command: python manage.py runserver 0.0.0.0:3000
    depends_on:
      - database
    volumes:
      - ./code:/code
    ports:
      - "3002:3000"
  database:
    container_name: shopify_db
    image: postgres:16.3
    environment:
      POSTGRES_DB: shopify_db
      POSTGRES_USER: shopify_user
      POSTGRES_PASSWORD: shopify_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5536:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/pgdata